//
// Generated file, do not edit! Created by opp_msgc 4.0 from httptools/messages/httptMessages.msg.
//

#ifndef _HTTPTMESSAGES_M_H_
#define _HTTPTMESSAGES_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0400
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>httptools/messages/httptMessages.msg</tt> by opp_msgc.
 * <pre>
 * packet httptBaseMessage
 * {
 *     @omitGetVerb(true);
 *     string targetUrl; 				
 *     string originatorUrl = "";		
 *     int protocol = 11; 				
 *     bool keepAlive = true;			
 *     int serial = 0;					
 *     string heading = "";				
 *     string payload = "";				
 * }
 * </pre>
 */
class httptBaseMessage : public cPacket
{
  protected:
    opp_string targetUrl_var;
    opp_string originatorUrl_var;
    int protocol_var;
    bool keepAlive_var;
    int serial_var;
    opp_string heading_var;
    opp_string payload_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const httptBaseMessage&);

  public:
    httptBaseMessage(const char *name=NULL, int kind=0);
    httptBaseMessage(const httptBaseMessage& other);
    virtual ~httptBaseMessage();
    httptBaseMessage& operator=(const httptBaseMessage& other);
    virtual httptBaseMessage *dup() const {return new httptBaseMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * targetUrl() const;
    virtual void setTargetUrl(const char * targetUrl_var);
    virtual const char * originatorUrl() const;
    virtual void setOriginatorUrl(const char * originatorUrl_var);
    virtual int protocol() const;
    virtual void setProtocol(int protocol_var);
    virtual bool keepAlive() const;
    virtual void setKeepAlive(bool keepAlive_var);
    virtual int serial() const;
    virtual void setSerial(int serial_var);
    virtual const char * heading() const;
    virtual void setHeading(const char * heading_var);
    virtual const char * payload() const;
    virtual void setPayload(const char * payload_var);
};

inline void doPacking(cCommBuffer *b, httptBaseMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, httptBaseMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>httptools/messages/httptMessages.msg</tt> by opp_msgc.
 * <pre>
 * packet httptRequestMessage extends httptBaseMessage
 * {
 *     @omitGetVerb(true);			
 *     bool badRequest = false;	
 * }
 * </pre>
 */
class httptRequestMessage : public httptBaseMessage
{
  protected:
    bool badRequest_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const httptRequestMessage&);

  public:
    httptRequestMessage(const char *name=NULL, int kind=0);
    httptRequestMessage(const httptRequestMessage& other);
    virtual ~httptRequestMessage();
    httptRequestMessage& operator=(const httptRequestMessage& other);
    virtual httptRequestMessage *dup() const {return new httptRequestMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual bool badRequest() const;
    virtual void setBadRequest(bool badRequest_var);
};

inline void doPacking(cCommBuffer *b, httptRequestMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, httptRequestMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>httptools/messages/httptMessages.msg</tt> by opp_msgc.
 * <pre>
 * packet httptReplyMessage extends httptBaseMessage
 * {
 *     @omitGetVerb(true);
 *     int result = 0; 				
 *     int contentType = 0;			
 * }
 * </pre>
 */
class httptReplyMessage : public httptBaseMessage
{
  protected:
    int result_var;
    int contentType_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const httptReplyMessage&);

  public:
    httptReplyMessage(const char *name=NULL, int kind=0);
    httptReplyMessage(const httptReplyMessage& other);
    virtual ~httptReplyMessage();
    httptReplyMessage& operator=(const httptReplyMessage& other);
    virtual httptReplyMessage *dup() const {return new httptReplyMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int result() const;
    virtual void setResult(int result_var);
    virtual int contentType() const;
    virtual void setContentType(int contentType_var);
};

inline void doPacking(cCommBuffer *b, httptReplyMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, httptReplyMessage& obj) {obj.parsimUnpack(b);}


#endif // _HTTPTMESSAGES_M_H_
